version: '3.8'

services:
  postgres:
    image: postgres:16.8
    container_name: forum-postgres
    environment:
      POSTGRES_USER: forum_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD:-strongpassword123}
      POSTGRES_DB: forum_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forum_admin -d forum_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: