services:
  postgres:
    image: postgres:16.8
    container_name: forum-postgres
    environment:
      POSTGRES_USER: forum_admin
      POSTGRES_PASSWORD: strongpassword123  # Убрали переменную для простоты
      POSTGRES_DB: forum_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forum_admin -d forum_db"]
      interval: 10s
      timeout: 10s  # Увеличили таймаут
      retries: 10   # Увеличили количество попыток
    restart: unless-stopped

  main-service:
    build: ./main-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      DB_DSN: "host=forum-postgres user=forum_admin password=strongpassword123 dbname=forum_db port=5432 sslmode=disable"
      SECRET_KEY: "supersecretkey"
    restart: on-failure

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      DB_DSN: "host=forum-postgres user=forum_admin password=strongpassword123 dbname=forum_db port=5432 sslmode=disable"
      SECRET_KEY: "supersecretkey"
    restart: on-failure
  notification-service:
    build: ./notification-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - redis
    environment:
      DB_DSN: "host=forum-postgres user=forum_admin password=strongpassword123 dbname=forum_db port=5432 sslmode=disable"
      REDIS_ADDR: "redis:6379"
      EMAIL_ADDRESS: "-"
      EMAIL_PASSWORD: "-"
    restart: on-failure

  redis:
    image: redis:alpine
    container_name: forum-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
volumes:
  postgres_data: